{
 "title": "NGINX Servers Metrics111",
 "tags": [
  "nginx",
  "http"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Traffic (5m rate)",
   "type": "timeseries",
   "description": "Response sizes in bytes",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_size_bytes[5m])) by (instance)",
     "legendFormat": "response_size_bytes {{instance}}"
    }
   ]
  },
  {
   "title": "Total Response (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total[1m])) by (instance)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RAM Basic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) by (instance)",
     "legendFormat": "Total  {{instance}}"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance)",
     "legendFormat": "Used {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Used% ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))) by (instance)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Utulisation, Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Saturation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_load1_per_cpu:ratio{job=\"node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate1m{job=\"node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Net Saturation (Drops Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(instance:node_network_receive_drop_excluding_lo:rate1m{job=\"node\"}) by (instance)",
     "legendFormat": "Receive {{instance}}"
    },
    {
     "expr": "sum(instance:node_network_transmit_drop_excluding_lo:rate1m{job=\"node\"}) by (instance)",
     "legendFormat": "Transmit {{instance}}"
    }
   ]
  },
  {
   "title": "Net Utilisation (Bytes Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 22, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(instance:node_network_receive_bytes_excluding_lo:rate1m{job=\"node\"}) by (instance)",
     "legendFormat": "Receive {{instance}}"
    },
    {
     "expr": "sum(instance:node_network_transmit_bytes_excluding_lo:rate1m{job=\"node\"}) by (instance)",
     "legendFormat": "Transmit {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(instance:node_vmstat_pgmajfault:rate1m{job=\"node\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(instance:node_memory_utilisation:ratio{job=\"node\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}